# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "keks",
  "email": "keks@keks.ru",
  "type": "Pro",
  "password": "password"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks@keks.ru",
  "password": "password"
}

###

## Проверить токен пользователя

GET http://localhost:5000/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5hbWU0QG5hbWU0LnJ1IiwibmFtZSI6Im5hbWU0IiwiaWQiOiI2NjY0MzhlYTRmZDZlOWYzZmU4MDcxNjkiLCJpYXQiOjE3MTc4NDQ0NDcsImV4cCI6MTcxODAxNzI0N30.s15-2LH5tt7q7nrpgkRxI65kI1BUpBrHGAiOv9AigTg
###

## Отправить изображение

POST http://localhost:5000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/artyomklyukin/Desktop/
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##

###